name: Manage github teams
permissions:
    contents: write
on:
    workflow_dispatch:
        inputs:
            option:
                description: "Option"
                required: true
                type: choice
                options:
                    - Create team
                    - Delete team
                    - Update team
                    - Add member
                    - Remove member
                    - Add repository permissions
                    - Remove repository permissions
            team_name:
                description: "Team name"
                required: true
            team_description:
                description: "Team description"
                required: false            
            team_repo_permissions:
                description: "Repository access permissions for members of the team"
                required: false
            team_members:
                description: "Team member(s)"
                required: false

jobs:
    manage-teams:
        name: Create GitHub Team
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_PAT }}

            - name: Add execute permissions to script
              run: chmod +x scripts/manage-team.sh

            - name: Make changes to teams terraform file
              run: |
                  cd scripts
                  ./manage-team.sh "${{ inputs.option }}" "${{ inputs.team_name }}" "${{ inputs.team_description }}" "${{ inputs.team_repo_permissions }}" "${{ inputs.team_members }}"

            - name: Commit and push changes
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  ls
                  git add .
                  if ${{ inputs.option == 'Create team' }}; then
                        git commit -m "Create team: ${{ inputs.team_name }}"
                    elif ${{ inputs.option == 'Delete team' }}; then
                        git commit -m "Delete team: ${{ inputs.team_name }}"
                    elif ${{ inputs.option == 'Update team' }}; then
                        git commit -m "Update team: ${{ inputs.team_name }}"
                    elif ${{ inputs.option == 'Add member' }}; then
                        git commit -m "Add member(s) to team: ${{ inputs.team_name }}"
                    elif ${{ inputs.option == 'Remove member' }}; then
                        git commit -m "Remove member(s) from team: ${{ inputs.team_name }}"
                    fi
                  git push